### ISSUE TITLE
ComposingBuild的项目在AS中make project报错

### ISSUE THREAD

**Issue by wankey** [hi-dhl/ComposingBuilds-vs-buildSrc#2]
ComposingBuild的项目在AS中make project报错

Project directory '/Users/username/Downloads/ComposingBuilds-vs-buildSrc-master/Project-ComposingBuild/versionPlugin' is not part of the build defined by settings file '/Users/username/Downloads/ComposingBuilds-vs-buildSrc-master/Project-ComposingBuild/settings.gradle'. If this is an unrelated build, it must have its own settings file.

**Comment by hi-dhl** [comment]
@wankey  辛苦，请更新代码，在试一下

**Comment by hi-dhl** [comment]
@wankey  已经修复，辛苦，请更新代码，在试一下

**Comment by hi-dhl** [comment]
@wankey  注意这段话`includeBuild("../versionPlugin")` ，versionPlugin 插件，不能放到 project 下面，应该放到 project 以外的目录，或者和 project 同级目录，如下所示:

![image](https://user-images.githubusercontent.com/16751752/84627649-da50e800-af19-11ea-8936-2beb2497525d.png)

**Comment by wankey** [comment]
已正常

**Comment by MankinChung** [comment]
> @wankey 注意这段话`includeBuild("../versionPlugin")` ，versionPlugin 插件，不能放到 project 下面，应该放到 project 以外的目录，或者和 project 同级目录，如下所示:
> 
> ![image](https://user-images.githubusercontent.com/16751752/84627649-da50e800-af19-11ea-8936-2beb2497525d.png)

有个问题，放在项目外面，不在版本管控范围内了。新项目还可以以父目录作为根目录，但旧项目的话就改不了了

**Comment by hi-dhl** [comment]
有点不太明白，ComposingBuilds 在多项目更具有优势，新旧项目引用它应该直接就可以用了， 你说的 「不在版本管控范围内了」 这句话，你指的库的版本管理吗？

**Comment by MankinChung** [comment]
> 有点不太明白，ComposingBuilds 在多项目更具有优势，新旧项目引用它应该直接就可以用了， 你说的 「不在版本管控范围内了」 这句话，你指的库的版本管理吗？

我的意思是，要把VersionPlugin(主要是Versions)和项目一起加入git管理，做统一的版本管控。但是旧项目的话，是以项目路径作为git根目录的，项目外的VersionPlugin就不在git管理范围了

**Comment by hi-dhl** [comment]
@MankinChung  两个方案：
方案一： VersionPlugin 可以放在项目下，可以正常编译, 也不会影响 Jenkins 打包，不过clean 或者 make 的时候会提示 “not part of the build defined by settings file” 
方案二：将 VersionPlugin 当做一个 git 去管理就好了，旧项目可以直接引入，对项目本身不会有影响

**Comment by MankinChung** [comment]
@hi-dhl 嗯，方案二的submodule可以完美解决
