### ISSUE TITLE
使用Composing builds的缓存问题

### ISSUE THREAD

**Issue by l-w-h** [hi-dhl/ComposingBuilds-vs-buildSrc#3]
当lib文件的API发生变化时，会发现已修改的API方法找不到，且External Libraries列表下的版本号还是之前已经缓存的版本，导致找不到新的API，只有在重启AS才能找到新的API，可以优化下吗

**Comment by BCsl** [comment]
@l-w-h  这个应该要进行一下 Sync with Gradle Files 吧？

**Comment by hi-dhl** [comment]
@BCsl  感谢帮忙回复

**Comment by hi-dhl** [comment]
@l-w-h

**Comment by hi-dhl** [comment]
@l-w-h  AndroidStudio 有个按钮 ，如下图所示，点击一下就可以了

![image](https://user-images.githubusercontent.com/16751752/88252877-60630a00-cce2-11ea-86fc-d3876496dabd.png)

**Comment by hi-dhl** [comment]
@l-w-h  不同 AndroidStudio 版本，图标和位置可能不同，也可以按照如下图所示路径（File > Sync Project with Gradle Files.），找到这个按钮

![image](https://user-images.githubusercontent.com/16751752/88252961-a61fd280-cce2-11ea-9789-da8d5a90382c.png)
