### ISSUE TITLE
是否有方法可以统一为每个模块引入插件

### ISSUE THREAD

**Issue by cbfg5210** [hi-dhl/ComposingBuilds-vs-buildSrc#5]
目前来说，每次引入插件的时候都要在 build.gradle 中添加：
plugins{
    id "com.hi.dhl.plugin"
}
是否有方法可以统一为每个 module 引入这个插件呢？

另外有个问题想请教下，为什么用以下引入插件的方式不行呢：
apply plugin :  "com.hi.dhl.plugin"

**Comment by cbfg5210** [comment]
> 目前来说，每次引入插件的时候都要在 build.gradle 中添加：
> plugins{
> id "com.hi.dhl.plugin"
> }
> 是否有方法可以统一为每个 module 引入这个插件呢？
> 
> 另外有个问题想请教下，为什么用以下引入插件的方式不行呢：
> apply plugin : "com.hi.dhl.plugin"

找文档看了一下，知道了 plugins{} 和 apply plugin 的区别：
https://stackoverflow.com/questions/32352816/what-the-difference-in-applying-gradle-plugin，

从官方文档中发现了一个全局引入插件的方法，这样就不用每个模块都引入一次插件了。在 root build.gradle 中添加：

//The use of apply false adds the plugin to the overall project, but does not add it to the root project.
plugins {
    id 'plugin.version' apply false
}

**Comment by hi-dhl** [comment]
@cbfg5210  可以的，在多项目构建中，可以把插件应用在所有子项目中，也可以把某个插件应用到其中部分子项目中，我已经修复了 Project-ComposingBuild 的问题，并在 gradle 中添加了注释，点击下方链接前往查看

https://github.com/hi-dhl/ComposingBuilds-vs-buildSrc/blob/a339c8a24764f8fd212768286cc941aaac48b4ad/Project-ComposingBuild/build.gradle#L20-L50

**Comment by cbfg5210** [comment]
@hi-dhl 感谢你的回复！我想应该是我把插件模块放到了项目目录下的原因吧，所以 apply plugin 的时候提示找不到，但是 plugins{} 就行，这个应该是新旧 api 的差异吧。我在你的项目基础上结合个人想法做了一点修改，新起了一个项目：[ComposingBuildDemo](https://gitee.com/cbfg5210/ComposingBuildDemo)，欢迎你来就其中可能存在的问题提出意见和建议。
![image](https://user-images.githubusercontent.com/12880545/96206109-c76b2480-0f9a-11eb-873d-4fa96d9da584.png)

**Comment by hi-dhl** [comment]
@cbfg5210  好的，我看一下
