### ISSUE TITLE
VersionPlugin放外面，多项目引用的问题

### ISSUE THREAD

**Issue by zhoujia456888** [hi-dhl/ComposingBuilds-vs-buildSrc#6]
VersionPlugin放外面的话。BuildConfig下的versionCode和versionName就失去了意义了。不同项目的版本号应该是不一样。
另外不同的项目引用的lib可能是不一样的， DependencyManager.kt里的数据会越来越多，有些项目不一定会用到lib的都写进来了。

解决方法：
versionCode和versionName的问题应该还是要在项目下的build.gradle中去填写。BuildConfig里面写意义不大
DependencyManager这个文件到后面估计要拆分掉。感觉在项目中填一大堆不相关的lib有点不舒服。显得很多余。。。

**Comment by hi-dhl** [comment]
非常感谢你的提交：

1. versionCode 和 versionName 是应该放在 build.gradle，这个当时只是做了一个示例，需要根据实际项目做一些调整
2. DependencyManager 中的 lib 作为演示之用，在实际项目中要根据自己项目中使用的 lib 做一些调整
3. 在实际项目中，通常引用的 lib 是非常的多的，DependencyManager 是需要做拆分的
