### ISSUE TITLE
composing-build文件夹存放问题[讨论]

### ISSUE THREAD

**Issue by xiaoxincoder** [hi-dhl/ComposingBuilds-vs-buildSrc#7]
我这里是可以将composing-build插件放到project下面的, 在settings.gradle引入的时候: "./plugin-name", 这样就可以了

**Comment by hi-dhl** [comment]
嗯嗯，示例中也是这么做的
https://github.com/hi-dhl/ComposingBuilds-vs-buildSrc/blob/10c65a3e9139d99c4880f27b59ab55ab16ce5689/Project-ComposingBuild/settings.gradle#L2

**Comment by xiaoxincoder** [comment]
你这里是 "../插件名称", 这样不方便, 我用的"./插件名称",  插件module放到了工程目录的下面, 事例是放在了和工程目录同一个文件夹下面

**Comment by hi-dhl** [comment]
懂你的意思了， 之前放在 project 会有一个问题，可以查看 issue #2 ， 最新的 AS 好像已经修复这个问题了

**Comment by xiaoxincoder** [comment]
嗯嗯对的, 之前的写法很不方便. studio 跟个屎一样, 4.1以上的我现在都不敢安装, 动一下就卡死!!

**Comment by BinarySatan** [comment]
4.2.1版本在project目录下放VersionPlugin clean project 还是会出现 If this is an unrelated build, it must have its own settings file.

**Comment by hi-dhl** [comment]
> 4.2.1版本在project目录下放VersionPlugin clean project 还是会出现 If this is an unrelated build, it must have its own settings file.

这个版本没修复，试一下  Android Studio Arctic Fox 的版本
